### ISSUE TITLE
Syntax duplication

### ISSUE THREAD

**Issue by sidmani** [inem/hamdown#1]
According to the spec, a level-2 header could be either:  
`## Header`  
or  
```
%h2
    Header
```  
Syntax duplication is a generally confusing for the end-user, so I think something like `##.f2.helvetica` could work better. Thoughts? 

I'm interested in this because I maintain [Anodize](https://github.com/sidmani/anodize), which is a static site generator that currently uses markdown + YAML + liquid templates, and a better language could be useful.

**Comment by inem** [comment]
I would leave both options. Because the idea is to be able to use both HAML and Markdown within one 
markup language, and not to invent a new flavor of Markdown.

I personally would use `##` notation for a static content, and HAML syntax `%h2` for parts being generated with Ruby.

**Comment by sidmani** [comment]
I see. I might write a language of my own then 😁
