### ISSUE TITLE
Rename to MarkHAML

### ISSUE THREAD

**Issue by bobwaycott** [inem/hamdown#3]
Credit goes to: https://news.ycombinator.com/item?id=17314309

**Comment by joallard** [comment]
...
...
...I don't get it.

**Comment by Odaeus** [comment]
![Mark Hamill](https://media.giphy.com/media/3owzVYjZSzuFivWpHi/giphy.gif)

**Comment by ronnidc** [comment]
Harkdown

**Comment by mcmire** [comment]
MarkHaml is funny, but IMO if this is going to be a legitimate project (and I think it should), we should name it something less gimmicky. Hamdown seems fine to me, tbh. If we want something less mashed-up, then perhaps Markl? But honestly I can see this being bikeshed until the cows come home.

**Comment by inem** [comment]
Love all the suggestions, but I prefer to stick with Hamdown. I already have a great logo idea for that name :)
